# Generated by Django 5.1.15 on 2026-05-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('service', models.CharField(choices=[('geological_consulting', 'Geologik konsalting'), ('comprehensive_project', 'Kompleks loyiha tayyorlash'), ('exploration_works', 'Geologik tadqiqot ishlari'), ('mre_report', 'MRE hisobot tayyorlash'), ('geochemical_research', 'Geokimyoviy tadqiqot'), ('geophysical_research', 'Geofizik tadqiqot'), ('structural_studies', 'Maxsus strukturaviy tadqiqotlar'), ('satellite_processing', "Sun'iy yo'ldosh tasvirini qayta ishlash"), ('ai_ml_prediction', 'AI / ML kon bashorati'), ('qaqc_crm', "QA/QC va CRM qo'llab-quvvatlash"), ('other', 'Boshqa / hali aniq emas')], default='other', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, help_text="Admin javob berdi yoki yo'q")),
            ],
            options={
                'verbose_name': "Bog'lanish so'rovi",
                'verbose_name_plural': "Bog'lanish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter obunachi',
                'verbose_name_plural': 'Newsletter obunachilari',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
