# Generated by Django 5.1.15 on 2026-05-10 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Tartib raqami: '01', '02', '5.1', va h.k.", max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_tr', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_tr', models.TextField(null=True)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG markup (path d=..., circle, line, va h.k.)')),
                ('is_featured', models.BooleanField(default=False, help_text="'NEW' badge bilan ko'rsatish (masalan AI/ML uchun)")),
                ('order', models.PositiveIntegerField(default=0, help_text='Saralash tartibi')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text="Agar bu sub-xizmat bo'lsa, ota xizmatni tanlang", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='services.service')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
                'ordering': ['order', 'number'],
            },
        ),
    ]
