# Generated by Django 6.0.5 on 2026-05-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='outcome',
            field=models.TextField(blank=True, help_text='OUTCOME: bu xizmat qanday natijani beradi'),
        ),
        migrations.AddField(
            model_name='service',
            name='outcome_en',
            field=models.TextField(blank=True, help_text='OUTCOME: bu xizmat qanday natijani beradi', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='outcome_ru',
            field=models.TextField(blank=True, help_text='OUTCOME: bu xizmat qanday natijani beradi', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='outcome_tr',
            field=models.TextField(blank=True, help_text='OUTCOME: bu xizmat qanday natijani beradi', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='outcome_uz',
            field=models.TextField(blank=True, help_text='OUTCOME: bu xizmat qanday natijani beradi', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='stages',
            field=models.CharField(blank=True, help_text='Vergul bilan ajratilgan bosqich kalitlari: desktop,target,explore,mre,scoping,pfs', max_length=120),
        ),
    ]
