# Generated by Django 5.1.15 on 2026-05-10 21:05

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('name_uz', models.CharField(max_length=80, null=True)),
                ('name_ru', models.CharField(max_length=80, null=True)),
                ('name_en', models.CharField(max_length=80, null=True)),
                ('name_tr', models.CharField(max_length=80, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_uz', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('title_tr', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField(help_text="Kartada ko'rinadigan qisqa tavsif", max_length=500)),
                ('excerpt_uz', models.TextField(help_text="Kartada ko'rinadigan qisqa tavsif", max_length=500, null=True)),
                ('excerpt_ru', models.TextField(help_text="Kartada ko'rinadigan qisqa tavsif", max_length=500, null=True)),
                ('excerpt_en', models.TextField(help_text="Kartada ko'rinadigan qisqa tavsif", max_length=500, null=True)),
                ('excerpt_tr', models.TextField(help_text="Kartada ko'rinadigan qisqa tavsif", max_length=500, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_tr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/')),
                ('read_time', models.PositiveIntegerField(default=5, help_text="O'qish vaqti (daqiqalarda)")),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog postlar',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
